# Generated by Django 6.0.2 on 2026-02-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roll',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('principal', 'principal'), ('teacher', 'teacher'), ('parent', 'parent')], default='parent', max_length=20),
        ),
    ]
