# Generated by Django 6.0.2 on 2026-03-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_principalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('principal', 'principal'), ('teacher', 'teacher'), ('student', 'student'), ('parent', 'parent')], default='principal', max_length=20),
        ),
    ]
