# Generated by Django 6.0.2 on 2026-03-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='password',
            field=models.CharField(default='parent@123', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
