# Generated by Django 6.0.2 on 2026-03-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_parent_password_parent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='username',
            field=models.CharField(default='null', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
