# Generated by Django 6.0.2 on 2026-03-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_alter_parent_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('principal', 'principal'), ('teacher', 'teacher'), ('student', 'student'), ('parent', 'parent')], default='parent', max_length=20),
        ),
    ]
