# Generated by Django 6.0.2 on 2026-02-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Araval', 'Araval'), ('Nilgiri', 'Nilgiri'), ('Shivalik', 'Shivalik'), ('Udaygiri', 'Udaygiri')], max_length=20)),
                ('category', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
            ],
        ),
    ]
