# Generated by Django 6.0.2 on 2026-02-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='category',
            new_name='house_category',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='name',
            new_name='house_name',
        ),
    ]
