# Generated by Django 6.0.2 on 2026-02-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_housemaster'),
        ('teachers', '0002_teacherprofile_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='housemaster',
            unique_together={('teacher', 'house')},
        ),
    ]
