# Generated by Django 6.0.2 on 2026-03-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('classes', '0001_initial'),
        ('teachers', '0004_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together={('classroom', 'academic_year'), ('teacher', 'academic_year')},
        ),
    ]
