# Generated by Django 6.0.2 on 2026-03-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_timetable_day_and_more'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('classroom', 'time_slot', 'day', 'academic_year')},
        ),
    ]
