# Generated by Django 6.0.2 on 2026-03-07 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_classteacher_classroom'),
        ('classes', '0002_exam_reportcard_subjectexam_studentmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='classroom',
        ),
        migrations.AddField(
            model_name='exam',
            name='class_name',
            field=models.CharField(default='nill', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_exam_subject', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
            ],
            options={
                'unique_together': {('classroom', 'subject')},
            },
        ),
    ]
