# Generated by Django 6.0.2 on 2026-03-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_classteacher_classroom'),
        ('classes', '0003_remove_exam_classroom_exam_class_name_classsubject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectexam',
            unique_together={('exam', 'subject')},
        ),
    ]
