# Generated by Django 6.0.2 on 2026-03-07 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('houses', '0004_alter_housemaster_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houseattendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='houseattendance',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_attendance', to='houses.house'),
        ),
    ]
