# Generated by Django 6.0.2 on 2026-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='present_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
